---
name: Test

on:
  push:
    branches:
      - main
      - renovate/**
  pull_request:
    branches:
      - main
  
env:
  PYTHON_VERSION: 3.13

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          enable-cache: true
          cache-dependency-glob: "requirements_dev.txt"
          activate-environment: true
      - name: Install dependencies
        run: |
          uv pip install -r requirements_dev.txt
      - name: Test with pytest
        run: |
          pytest
